# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: "Publish Images (download.eclipse.org)"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-disk-images:
    name: publish-disk-images
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          mkdir -p _build/outputs

      - name: Download Images from GitHub Dev Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh release download dev --repo eclipse-autosd/eclipse-autosd
        working-directory: _build/outputs

      - name: SCP Artifacts to download.eclipse.org
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1
        with:
          host: projects-storage.eclipse.org
          username: ${{ secrets.SCP_USERNAME }}
          key: ${{ secrets.SCP_KEY }}
          passphrase: ${{ secrets.SCP_PASSPHRASE }}
          source: "_build/outputs/*"
          target: "/home/data/httpd/download.eclipse.org/autosd/disk-images/"
          strip_components: 2
